import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Header from "~/components/header";
import Newsletter from "~/components/newsletter";
import Footer from "~/components/footer";
import { Toaster } from "~/components/ui/sonner";
import { CartProvider } from "~/context/cart-context";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <CartProvider>
          <Header />
          <div className="flex min-h-screen flex-col bg-gray-100 pt-20">
            <div className="flex-grow">{children}</div>
            <Newsletter />
            <Footer />
          </div>
        </CartProvider>
        <Toaster />
      </body>
    </html>
  );
}
